
# Run cellAlign

## Diffusion Component pseudo-time

```{}
library(tictoc)
library(cellAlign)
# MM057
print("MM057")
print("Getting data...")
load("/ddn1/vol1/staging/leuven/stg_00002/lcb/zkalender/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/3.MM057_SOX/00.RData/MM057_monocle_obj.RData", envir = MM057.monocle <- new.env())

three.MM.lines.DC.alignment<-readRDS(file = "three_MM_lines_DC_alignment.rds.gz")
## Get pseudotime
MM057.DC.pseudotime<-1-three.MM.lines.DC.alignment$MM057$princurve.pseudo.time.scaled


"TL"%in%MM057.monocle$MM057_cds$Experiment 
"TL"%in%MM074.monocle$MM074_cds$Experiment
"TL"%in%MM087.monocle$MM087_cds$Experiment

## Run cellAlign
tic()
# Interpolation and scaling
print("Interpolating data...")
numPts = 200
MM057.DC.inter.global <- cellAlign::interWeights(expDataBatch = MM057.monocle$MM057_cds@assayData$exprs, trajCond = MM057.DC.pseudotime[colnames(MM057.monocle$MM057_cds@assayData$exprs)], winSz = 0.1, numPts = numPts)
toc()

print("Scaling interpolated data...")
tic()
MM057.DC.inter.global.scaled <- cellAlign::scaleInterpolate(MM057.DC.inter.global)
toc()

print("Saving data...")

three.MM.lines.DC.cellAlign<-list()
three.MM.lines.DC.cellAlign[["MM057"]]<-list()
three.MM.lines.DC.cellAlign$MM057[["cellAlign.inter.global"]]<-MM057.DC.inter.global
three.MM.lines.DC.cellAlign$MM057[["cellAlign.inter.global.scaled"]]<-MM057.DC.inter.global.scaled

saveRDS(object = three.MM.lines.DC.cellAlign, "three_MM_lines_DC_cellAlign.rds.gz")
print("Done!")

# MM074
print("MM074")
print("Getting data...")

load("/ddn1/vol1/staging/leuven/stg_00002/lcb/kspan/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/5.MM074_SOX/00.RData/MM074_monocle_obj.RData", envir = MM074.monocle <- new.env())

MM074.DC.pseudotime<-three.MM.lines.DC.alignment$MM074$princurve.pseudo.time.scaled

library(tictoc)
tic()
# Interpolation and scaling
print("Interpolating data...")
numPts = 200
MM074.DC.inter.global <- cellAlign::interWeights(expDataBatch = MM074.monocle$MM074_cds@assayData$exprs, trajCond = MM074.DC.pseudotime[colnames(MM074.monocle$MM074_cds@assayData$exprs)], winSz = 0.1, numPts = numPts)
toc()

print("Scaling interpolated data...")
tic()
MM074.DC.inter.global.scaled <- cellAlign::scaleInterpolate(MM074.DC.inter.global)
toc()

print("Saving data...")

three.MM.lines.DC.cellAlign[["MM074"]]<-list()
three.MM.lines.DC.cellAlign$MM074[["cellAlign.inter.global"]]<-MM074.DC.inter.global
three.MM.lines.DC.cellAlign$MM074[["cellAlign.inter.global.scaled"]]<-MM074.DC.inter.global.scaled

saveRDS(object = three.MM.lines.DC.cellAlign, "three_MM_lines_DC_cellAlign.rds.gz")
print("Done!")

# MM087
print("MM087")
print("Getting data...")
load("/ddn1/vol1/staging/leuven/stg_00002/lcb/zkalender/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/7.M0087_SOX/00.RData/MM087_monocle_obj.RData", envir = MM087.monocle <- new.env())

MM087.DC.pseudotime<-1-three.MM.lines.DC.alignment$MM087$princurve.pseudo.time.scaled

library(tictoc)
tic()
# Interpolation and scaling
print("Interpolating data...")
numPts = 200
MM087.DC.inter.global <- cellAlign::interWeights(expDataBatch = MM087.monocle$MM087_cds@assayData$exprs, trajCond = MM087.DC.pseudotime[colnames(MM087.monocle$MM087_cds@assayData$exprs)], winSz = 0.1, numPts = numPts)
toc()

print("Scaling interpolated data...")
tic()
MM087.DC.inter.global.scaled <- cellAlign::scaleInterpolate(MM087.DC.inter.global)
toc()

print("Saving data...")

three.MM.lines.DC.cellAlign[["MM087"]]<-list()
three.MM.lines.DC.cellAlign$MM087[["cellAlign.inter.global"]]<-MM087.DC.inter.global
three.MM.lines.DC.cellAlign$MM087[["cellAlign.inter.global.scaled"]]<-MM087.DC.inter.global.scaled

saveRDS(object = three.MM.lines.DC.cellAlign, "three_MM_lines_DC_cellAlign.rds.gz")
print("Done!")
```

## SCORPIUS pseudo-time

```{r}
library(tictoc)
library(cellAlign)
# MM057
print("MM057")
print("Getting data...")
load("/ddn1/vol1/staging/leuven/stg_00002/lcb/zkalender/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/3.MM057_SOX/00.RData/MM057_monocle_obj.RData", envir = MM057.monocle <- new.env())
load("/ddn1/vol1/staging/leuven/stg_00002/lcb/zkalender/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/3.MM057_SOX/00.RData/SCORPIUS_var_genes_workspace.RData")

## Get pseudotime
MM057.SCORPIUS.pseudotime<-traj$time

## Run cellAlign
tic()
# Interpolation and scaling
print("Interpolating data...")
numPts = 200
MM057.SCORPIUS.inter.global <- cellAlign::interWeights(expDataBatch = MM057.monocle$MM057_cds@assayData$exprs, trajCond = MM057.SCORPIUS.pseudotime[colnames(MM057.monocle$MM057_cds@assayData$exprs)], winSz = 0.1, numPts = numPts)
toc()

print("Scaling interpolated data...")
tic()
MM057.SCORPIUS.inter.global.scaled <- cellAlign::scaleInterpolate(MM057.SCORPIUS.inter.global)
toc()

print("Saving data...")

three.MM.lines.SCORPIUS.alignment<-list()
three.MM.lines.SCORPIUS.alignment[["MM057"]]<-list()
three.MM.lines.SCORPIUS.alignment$MM057[["cellAlign.inter.global"]]<-MM057.SCORPIUS.inter.global
three.MM.lines.SCORPIUS.alignment$MM057[["cellAlign.inter.global.scaled"]]<-MM057.SCORPIUS.inter.global.scaled

saveRDS(object = three.MM.lines.SCORPIUS.alignment, "three_MM_lines_SCORPIUS_cellAlign.rds.gz")
print("Done!")

# MM074
print("MM074")
print("Getting data...")

load("/ddn1/vol1/staging/leuven/stg_00002/lcb/kspan/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/5.MM074_SOX/00.RData/MM074_monocle_obj.RData", envir = MM074.monocle <- new.env())
three.MM.lines.DC.alignment<-readRDS(file = "three_MM_lines_DC_alignment.rds.gz")
load("/ddn1/vol1/staging/leuven/stg_00002/lcb/zkalender/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/5.MM074_SOX/00.RData/SCORPIUS_var_genes_workspace.RData", envir = MM074.SCORPIUS <- new.env())

MM074.SCORPIUS.pseudotime<-MM074.SCORPIUS$traj$time

library(tictoc)
tic()
# Interpolation and scaling
print("Interpolating data...")
numPts = 200
MM074.SCORPIUS.inter.global <- cellAlign::interWeights(expDataBatch = MM074.monocle$MM074_cds@assayData$exprs, trajCond = MM074.SCORPIUS.pseudotime[colnames(MM074.monocle$MM074_cds@assayData$exprs)], winSz = 0.1, numPts = numPts)
toc()

print("Scaling interpolated data...")
tic()
MM074.SCORPIUS.inter.global.scaled <- cellAlign::scaleInterpolate(MM074.SCORPIUS.inter.global)
toc()

print("Saving data...")

three.MM.lines.SCORPIUS.alignment[["MM074"]]<-list()
three.MM.lines.SCORPIUS.alignment$MM074[["cellAlign.inter.global"]]<-MM074.SCORPIUS.inter.global
three.MM.lines.SCORPIUS.alignment$MM074[["cellAlign.inter.global.scaled"]]<-MM074.SCORPIUS.inter.global.scaled

saveRDS(object = three.MM.lines.SCORPIUS.alignment, "three_MM_lines_SCORPIUS_cellAlign.rds.gz")
print("Done!")

# MM087
print("MM087")
print("Getting data...")
load("/ddn1/vol1/staging/leuven/stg_00002/lcb/zkalender/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/7.M0087_SOX/00.RData/SCORPIUS_var_genes_workspace.RData", envir = MM087.SCORPIUS <- new.env())
load("/ddn1/vol1/staging/leuven/stg_00002/lcb/zkalender/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/7.M0087_SOX/00.RData/MM087_monocle_obj.RData", envir = MM087.monocle <- new.env())

MM087.SCORPIUS.pseudotime<-MM087.SCORPIUS$traj$time

library(tictoc)
tic()
# Interpolation and scaling
print("Interpolating data...")
numPts = 200
MM087.SCORPIUS.inter.global <- cellAlign::interWeights(expDataBatch = MM087.monocle$MM087_cds@assayData$exprs, trajCond = MM087.SCORPIUS.pseudotime[colnames(MM087.monocle$MM087_cds@assayData$exprs)], winSz = 0.1, numPts = numPts)
toc()

print("Scaling interpolated data...")
tic()
MM087.SCORPIUS.inter.global.scaled <- cellAlign::scaleInterpolate(MM087.SCORPIUS.inter.global)
toc()

print("Saving data...")

three.MM.lines.SCORPIUS.alignment[["MM087"]]<-list()
three.MM.lines.SCORPIUS.alignment$MM087[["cellAlign.inter.global"]]<-MM087.SCORPIUS.inter.global
three.MM.lines.SCORPIUS.alignment$MM087[["cellAlign.inter.global.scaled"]]<-MM087.SCORPIUS.inter.global.scaled

saveRDS(object = three.MM.lines.SCORPIUS.alignment, "three_MM_lines_SCORPIUS_cellAlign.rds.gz")
print("Done!")

```

## Monocle pseudo-time
```
library(tictoc)
library(cellAlign)
source("functions.R")
# MM057
print("MM057")
print("Getting data...")
load("/ddn1/vol1/staging/leuven/stg_00002/lcb/zkalender/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/3.MM057_SOX/00.RData/MM057_monocle_obj.RData", envir = MM057.monocle <- new.env())

## Get pseudotime
MM057.monocle.pseudotime<-MM057.monocle$MM057_cds@phenoData@data$Pseudotime
names(MM057.monocle.pseudotime)<-row.names(MM057.monocle$MM057_cds@phenoData@data)
MM057.monocle.pseudotime<-range01(x = MM057.monocle.pseudotime)

## Run cellAlign
tic()
# Interpolation and scaling
print("Interpolating data...")
numPts = 200
MM057.monocle.inter.global <- cellAlign::interWeights(expDataBatch = MM057.monocle$MM057_cds@assayData$exprs, trajCond = MM057.monocle.pseudotime[colnames(MM057.monocle$MM057_cds@assayData$exprs)], winSz = 0.1, numPts = numPts)
toc()

print("Scaling interpolated data...")
tic()
MM057.monocle.inter.global.scaled <- cellAlign::scaleInterpolate(MM057.monocle.inter.global)
toc()

print("Saving data...")

three.MM.lines.monocle.alignment<-list()
three.MM.lines.monocle.alignment[["MM057"]]<-list()
three.MM.lines.monocle.alignment$MM057[["cellAlign.inter.global"]]<-MM057.monocle.inter.global
three.MM.lines.monocle.alignment$MM057[["cellAlign.inter.global.scaled"]]<-MM057.monocle.inter.global.scaled

saveRDS(object = three.MM.lines.monocle.alignment, "three_MM_lines_monocle_cellAlign.rds.gz")
print("Done!")

# MM074
print("MM074")
print("Getting data...")

load("/ddn1/vol1/staging/leuven/stg_00002/lcb/kspan/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/5.MM074_SOX/00.RData/MM074_monocle_obj.RData", envir = MM074.monocle <- new.env())

MM074.monocle.pseudotime<-MM074.monocle$MM074_cds@phenoData@data$Pseudotime
names(MM074.monocle.pseudotime)<-row.names(MM074.monocle$MM074_cds@phenoData@data)
MM074.monocle.pseudotime<-range01(x = MM074.monocle.pseudotime)

library(tictoc)
tic()
# Interpolation and scaling
print("Interpolating data...")
numPts = 200
MM074.monocle.inter.global <- cellAlign::interWeights(expDataBatch = MM074.monocle$MM074_cds@assayData$exprs, trajCond = MM074.monocle.pseudotime[colnames(MM074.monocle$MM074_cds@assayData$exprs)], winSz = 0.1, numPts = numPts)
toc()

print("Scaling interpolated data...")
tic()
MM074.monocle.inter.global.scaled <- cellAlign::scaleInterpolate(MM074.monocle.inter.global)
toc()

print("Saving data...")

three.MM.lines.monocle.alignment[["MM074"]]<-list()
three.MM.lines.monocle.alignment$MM074[["cellAlign.inter.global"]]<-MM074.monocle.inter.global
three.MM.lines.monocle.alignment$MM074[["cellAlign.inter.global.scaled"]]<-MM074.monocle.inter.global.scaled

saveRDS(object = three.MM.lines.monocle.alignment, "three_MM_lines_monocle_cellAlign.rds.gz")
print("Done!")

# MM087
print("MM087")
print("Getting data...")
load("/ddn1/vol1/staging/leuven/stg_00002/lcb/zkalender/scRNA_seq_melanoma/analysis_40k/20.analysis_with_sub_matrices/7.M0087_SOX/00.RData/MM087_monocle_obj.RData", envir = MM087.monocle <- new.env())

MM087.monocle.pseudotime<-MM087.monocle$MM087_cds@phenoData@data$Pseudotime
names(MM087.monocle.pseudotime)<-row.names(MM087.monocle$MM087_cds@phenoData@data)
MM087.monocle.pseudotime<-range01(x = MM087.monocle.pseudotime)

library(tictoc)
tic()
# Interpolation and scaling
print("Interpolating data...")
numPts = 200
MM087.monocle.inter.global <- cellAlign::interWeights(expDataBatch = MM087.monocle$MM087_cds@assayData$exprs, trajCond = MM087.monocle.pseudotime[colnames(MM087.monocle$MM087_cds@assayData$exprs)], winSz = 0.1, numPts = numPts)
toc()

print("Scaling interpolated data...")
tic()
MM087.monocle.inter.global.scaled <- cellAlign::scaleInterpolate(MM087.monocle.inter.global)
toc()

print("Saving data...")

three.MM.lines.monocle.alignment[["MM087"]]<-list()
three.MM.lines.monocle.alignment$MM087[["cellAlign.inter.global"]]<-MM087.monocle.inter.global
three.MM.lines.monocle.alignment$MM087[["cellAlign.inter.global.scaled"]]<-MM087.monocle.inter.global.scaled

saveRDS(object = three.MM.lines.monocle.alignment, "three_MM_lines_monocle_cellAlign.rds.gz")
print("Done!")
```

# Generate the aligment plots

SCORPIUS vs DC vs monocle alignment,

## Load the libraries

```{r}
library(monocle)
library(cellAlign)
library(tictoc)
source("functions.R")
```

## Load the data (see Run cellAlign above section)

```{r}
three.MM.lines.DC.alignment<-readRDS(file = "three_MM_lines_DC_cellAlign.rds.gz")
three.MM.lines.SCORPIUS.alignment<-readRDS(file = "three_MM_lines_SCORPIUS_cellAlign.rds.gz")
three.MM.lines.monocle.alignment<-readRDS(file = "three_MM_lines_monocle_cellAlign.rds.gz")
rm(three.MM.lines.DC.alignment,three.MM.lines.SCORPIUS.alignment,three.MM.lines.monocle.alignment)
```


### MM057

#### Alignment

All genes,

```{r}
tic()
alignment = globalAlign(three.MM.lines.DC.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.SCORPIUS.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.DC.alignment$MM057$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.SCORPIUS.alignment$MM057$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM057_alignmentPlot_DCvsSCORPIUS.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```


```{r}
tic()
alignment = globalAlign(three.MM.lines.SCORPIUS.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.SCORPIUS.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.SCORPIUS.alignment$MM057$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.SCORPIUS.alignment$MM057$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
source("functions.R")
alignment$normalizedDistance
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM057_alignmentPlot_SCORPIUSvsSCORPIUS.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```


```{r}
tic()
alignment = globalAlign(three.MM.lines.DC.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.DC.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.DC.alignment$MM057$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.DC.alignment$MM057$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
source("functions.R")
alignment$normalizedDistance
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM057_alignmentPlot_DCvsDC.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

```{r}
tic()
alignment = globalAlign(three.MM.lines.DC.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.monocle.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.DC.alignment$MM057$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.monocle.alignment$MM057$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM057_alignmentPlot_DCvsMonocle.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

```{r}
tic()
alignment = globalAlign(three.MM.lines.SCORPIUS.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.monocle.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.SCORPIUS.alignment$MM057$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.monocle.alignment$MM057$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM057_alignmentPlot_SCORPIUSvsMonocle.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

```{r}
tic()
alignment = globalAlign(three.MM.lines.monocle.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.monocle.alignment$MM057$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.monocle.alignment$MM057$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.monocle.alignment$MM057$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM057_alignmentPlot_MonoclevsMonocle.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

### MM074

#### Alignment

All genes,

```{r}
tic()
alignment = globalAlign(three.MM.lines.DC.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.SCORPIUS.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.DC.alignment$MM074$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.SCORPIUS.alignment$MM074$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM074_alignmentPlot_DCvsSCORPIUS.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```


```{r}
tic()
alignment = globalAlign(three.MM.lines.SCORPIUS.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.SCORPIUS.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.SCORPIUS.alignment$MM074$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.SCORPIUS.alignment$MM074$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
source("functions.R")
alignment$normalizedDistance
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM074_alignmentPlot_SCORPIUSvsSCORPIUS.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```


```{r}
tic()
alignment = globalAlign(three.MM.lines.DC.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.DC.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.DC.alignment$MM074$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.DC.alignment$MM074$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
source("functions.R")
alignment$normalizedDistance
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM074_alignmentPlot_DCvsDC.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

```{r}
tic()
alignment = globalAlign(three.MM.lines.DC.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.monocle.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.DC.alignment$MM074$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.monocle.alignment$MM074$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM074_alignmentPlot_DCvsMonocle.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

```{r}
tic()
alignment = globalAlign(three.MM.lines.SCORPIUS.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.monocle.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.SCORPIUS.alignment$MM074$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.monocle.alignment$MM074$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM074_alignmentPlot_SCORPIUSvsMonocle.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

```{r}
tic()
alignment = globalAlign(three.MM.lines.monocle.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.monocle.alignment$MM074$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.monocle.alignment$MM074$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.monocle.alignment$MM074$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM074_alignmentPlot_MonoclevsMonocle.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

### MM087

#### Alignment

All genes,

```{r}
tic()
alignment = globalAlign(three.MM.lines.DC.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.SCORPIUS.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.DC.alignment$MM087$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.SCORPIUS.alignment$MM087$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM087_alignmentPlot_DCvsSCORPIUS.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```


```{r}
tic()
alignment = globalAlign(three.MM.lines.SCORPIUS.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.SCORPIUS.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.SCORPIUS.alignment$MM087$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.SCORPIUS.alignment$MM087$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
source("functions.R")
alignment$normalizedDistance
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM087_alignmentPlot_SCORPIUSvsSCORPIUS.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```


```{r}
tic()
alignment = globalAlign(three.MM.lines.DC.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.DC.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.DC.alignment$MM087$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.DC.alignment$MM087$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
source("functions.R")
alignment$normalizedDistance
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM087_alignmentPlot_DCvsDC.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

```{r}
tic()
alignment = globalAlign(three.MM.lines.DC.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.monocle.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.DC.alignment$MM087$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.monocle.alignment$MM087$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM087_alignmentPlot_DCvsMonocle.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

```{r}
tic()
alignment = globalAlign(three.MM.lines.SCORPIUS.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.monocle.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.SCORPIUS.alignment$MM087$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.monocle.alignment$MM087$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM087_alignmentPlot_SCORPIUSvsMonocle.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```

```{r}
tic()
alignment = globalAlign(three.MM.lines.monocle.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , three.MM.lines.monocle.alignment$MM087$cellAlign.inter.global.scaled$scaledData
                      , scores = list(query = three.MM.lines.monocle.alignment$MM087$cellAlign.inter.global.scaled$traj, 
                                      ref = three.MM.lines.monocle.alignment$MM087$cellAlign.inter.global.scaled$traj)
                      , sigCalc = F, numPerm = 200)
toc()
print(alignment$normalizedDistance)
alignment$ptShift<-NULL
x<-plotCellAlignment(alignment, title = NULL)
pdf(file = "figures/MM087_alignmentPlot_MonoclevsMonocle.pdf", width = 10, height = 10)
grid::grid.newpage()
grid::grid.draw(x$gtable)
dev.off()
```
