---
title: "Bulk RNAseq"
---

# KD experiments performed in 2 times
#!!!!! NTC1 for NFATC2KD
#!!!!! NTC2 for the rest

```{bash}
cd /media/lcb1/lcb/jwout/Data_Analyses/Git_Analyses/Rstudio/Bulk_RNA/Intermediate_state_KD_of_factors_Final/Allcounts
echo 'MM074_NTC1 MM074_NTC2 MM074_EGR3 MM074_NFATCKD MM087_NTC1 MM087_NTC2 MM087_EGR3 MM087_NFATCKD MM057_NTC1 MM057_NTC2 MM057_EGR3 MM057_NFATCKD' | tr ' ' '\t' > All.counts
paste MM074_NTC.counts MM074_NTC-KD.counts MM074_EGR3-KD.counts MM074_NFATC2_KD.counts MM087_NTC.counts MM087_NTC-KD.counts MM087_EGR3-KD.counts MM087_NFATC2_KD.counts RNA-seq_TruSeq_MM057_NTC_KD.counts MM057_NTC-KD.counts MM057_EGR3-KD.counts RNA-seq_TruSeq_MM057_NFATC2_KD.counts | cut -f1,2,4,6,8,10,12,14,16,18,20,22,24 | awk 'NR<55402' >> All.counts
```


```{r}
library(DESeq2)
library(org.Hs.eg.db)
library(AnnotationDbi)
library(msigdbr)
library(dplyr)

counts_KD_intermediate <- read.delim(file="Allcounts/All.counts")
counts_KD_intermediate
```

#EGR3-KD: multifactorial and with pre-filtering. (http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html)

```{r}
colnames(counts_KD_intermediate)
counts_EGR3KD_5787 <- counts_KD_intermediate[,c("MM087_NTC2", "MM087_EGR3", "MM057_NTC2", "MM057_EGR3")]
coldesign_1 <-data.frame(rep(c("NTC", "EGR3_KD"), 2))
coldesign_2 <-data.frame(c(rep(c("MM087"), 2), rep(c("MM057"), 2))) 
coldesign <- cbind(coldesign_1, coldesign_2)
colnames(coldesign)<-c("KD", "MMline")
Design<-coldesign
coldesign
dds_EGR3KD__5787_72h_MF <-DESeqDataSetFromMatrix(countData=counts_EGR3KD_5787, colData=coldesign , design= formula(~ MMline + KD))
dds_EGR3KD__5787_72h_MF<-DESeq(dds_EGR3KD__5787_72h_MF)

keep <- rowSums(counts(dds_EGR3KD__5787_72h_MF)) >= 10
dds_EGR3KD__5787_72h_MF_prefiltered <- dds_EGR3KD__5787_72h_MF[keep,]
#save(dds_EGR3KD__5787_72h_MF_prefiltered, file = "dds_EGR3KD__5787_72h_MF_prefiltered.RData")

res_EGR3KD_5787_72h_MF_prefiltered <-results(dds_EGR3KD__5787_72h_MF_prefiltered, contrast=c("KD","EGR3_KD","NTC"))
#save(res_EGR3KD_5787_72h_MF_prefiltered, file = "res_EGR3KD_5787_72h_MF_prefiltered.RData")
#write.table(res_EGR3KD_5787_72h_MF_prefiltered,file="res_EGR3KD_5787_72h_MF_prefiltered",sep="\t",quote=F)

norm_matrix_deseq_EGR3KD_5787_72h_MF_prefiltered <- counts(dds_EGR3KD__5787_72h_MF_prefiltered,normalized=T)

#save(norm_matrix_deseq_EGR3KD_5787_72h_MF_prefiltered, file= "norm_matrix_deseq_EGR3KD_5787_72h_MF_prefiltered.RData")
#write.table(norm_matrix_deseq_EGR3KD_5787_72h_MF_prefiltered, file="norm_matrix_deseq_EGR3KD_5787_72h_MF_prefiltered.txt", sep="\t", quote=F)

head(res_EGR3KD_5787_72h_MF_prefiltered[order(-res_EGR3KD_5787_72h_MF_prefiltered$log2FoldChange),], 30)
head(res_EGR3KD_5787_72h_MF_prefiltered[order(res_EGR3KD_5787_72h_MF_prefiltered$log2FoldChange),], 30)

dim(subset(res_EGR3KD_5787_72h_MF_prefiltered, padj<0.05 & log2FoldChange<0))
rownames(subset(res_EGR3KD_5787_72h_MF_prefiltered, padj<0.05 & log2FoldChange<0))

dim(subset(res_EGR3KD_5787_72h_MF_prefiltered, padj<0.05 & log2FoldChange>0))
rownames(subset(res_EGR3KD_5787_72h_MF_prefiltered, padj<0.05 & log2FoldChange>0))

EGR3KD_results <- res_EGR3KD_5787_72h_MF_prefiltered
EGR3KD_results$ID <- mapIds(org.Hs.eg.db, keys = rownames(EGR3KD_results), keytype = "SYMBOL", column = "ENTREZID")
EGR3KD_results <- as.data.frame(EGR3KD_results)
EGR3KD_results_noNA <- subset(EGR3KD_results, !is.na(ID))
dim(EGR3KD_results)
dim(EGR3KD_results_noNA)

#write.table(EGR3KD_results_noNA, file="EGR3KD_MF_5787_prefiltered_GSEA.txt", sep = "\t", quote=F)
```


#NFATC2-KD

```{r}
colnames(counts_KD_intermediate)
counts_NFATC2KD_5787 <- counts_KD_intermediate[,c("MM087_NTC1", "MM087_NFATCKD", "MM057_NTC1", "MM057_NFATCKD")]

coldesign_1 <-data.frame(rep(c("NTC", "NFATC2_KD"), 2))
coldesign_2 <-data.frame(c(rep(c("MM087"), 2), rep(c("MM057"), 2))) 
coldesign <- cbind(coldesign_1, coldesign_2)
colnames(coldesign)<-c("KD", "MMline")
Design<-coldesign
coldesign
dds_NFATC2KD__5787_72h_MF <-DESeqDataSetFromMatrix(countData=counts_NFATC2KD_5787, colData=coldesign , design= formula(~ MMline + KD))
dds_NFATC2KD__5787_72h_MF<-DESeq(dds_NFATC2KD__5787_72h_MF)

keep <- rowSums(counts(dds_NFATC2KD__5787_72h_MF)) >= 10
dds_NFATC2KD__5787_72h_MF_prefiltered <- dds_NFATC2KD__5787_72h_MF[keep,]

#save(dds_NFATC2KD__5787_72h_MF_prefiltered, file = "dds_NFATC2KD__5787_72h_MF_prefiltered.RData")

res_NFATC2KD__5787_72h_MF_prefiltered <-results(dds_NFATC2KD__5787_72h_MF_prefiltered, contrast=c("KD","NFATC2_KD","NTC"))
#save(res_NFATC2KD__5787_72h_MF_prefiltered, file = "res_NFATC2KD__5787_72h_MF_prefiltered.RData")
#write.table(res_NFATC2KD__5787_72h_MF_prefiltered,file="res_NFATC2KD__5787_72h_MF_prefiltered",sep="\t",quote=F)

norm_matrix_deseq_NFATC2KD_5787_72h_MF_prefiltered <- counts(dds_NFATC2KD__5787_72h_MF_prefiltered,normalized=T)

#save(norm_matrix_deseq_NFATC2KD_5787_72h_MF_prefiltered, file= "norm_matrix_deseq_NFATC2KD_5787_72h_MF_prefiltered.RData")
#write.table(norm_matrix_deseq_NFATC2KD_5787_72h_MF_prefiltered, file="norm_matrix_deseq_NFATC2KD_5787_72h_MF_prefiltered.txt", sep="\t", quote=F)

head(res_NFATC2KD__5787_72h_MF_prefiltered[order(-res_NFATC2KD__5787_72h_MF_prefiltered$log2FoldChange),], 30)
head(res_NFATC2KD__5787_72h_MF_prefiltered[order(res_NFATC2KD__5787_72h_MF_prefiltered$log2FoldChange),], 30)

dim(subset(res_NFATC2KD__5787_72h_MF_prefiltered, padj<0.1 & log2FoldChange<0))
rownames(subset(res_NFATC2KD__5787_72h_MF_prefiltered, padj<0.05 & log2FoldChange<0))

dim(subset(res_NFATC2KD__5787_72h_MF_prefiltered, padj<0.05 & log2FoldChange>0))
rownames(subset(res_NFATC2KD__5787_72h_MF_prefiltered, padj<0.05 & log2FoldChange>0))

NFATC2KD_results <- res_NFATC2KD__5787_72h_MF_prefiltered
NFATC2KD_results$ID <- mapIds(org.Hs.eg.db, keys = rownames(NFATC2KD_results), keytype = "SYMBOL", column = "ENTREZID")
NFATC2KD_results <- as.data.frame(NFATC2KD_results)
NFATC2KD_results_noNA <- subset(NFATC2KD_results, !is.na(ID))
dim(NFATC2KD_results)
dim(NFATC2KD_results_noNA)
#write.table(NFATC2KD_results_noNA, file="NFATC2KD_MF_5787_prefiltered_GSEA.txt", sep = "\t", quote=F)

```