---
title: "Bulk RNAseq THZ2 treatment"
---
# merging of counts files
```{bash}
cd /media/lcb1/lcb/jwout/Data_Analyses/Data/HiSeq4000_20190327_THZ2_TYR/Allcounts
echo 'MM057_6h_DMSO MM074_6h_DMSO MM087_6h_DMSO MM057_6h_THZ2 MM074_6h_THZ2 MM087_6h_THZ2 MM057_48h_DMSO MM074_48h_DMSO MM087_48h_DMSO MM057_48h_THZ2 MM074_48h_THZ2 MM087_48h_THZ2' | tr ' ' '\t' > All_THZ2_counts
paste THM__0153d0__MM057_6h_DMSO_q4_sorted.counts THM__3146fb__MM074_6h_DMSO_q4_sorted.counts THM__b07503__MM087_6h_DMSO_q4_sorted.counts THM__d6166a__MM057_6h_THZ2_q4_sorted.counts THM__ba3703__MM074_6h_THZ2_q4_sorted.counts THM__d4b647__MM087_6h_THZ2_q4_sorted.counts THM__f42256__MM057_48h_DMSO_q4_sorted.counts THM__526b6f__MM074_48h_DMSO_q4_sorted.counts THM__100f5e__MM087_48h_DMSO_q4_sorted.counts THM__f38cc9__MM057_48h_THZ2_q4_sorted.counts THM__083e58__MM074_48h_THZ2_q4_sorted.counts THM__8a090d__MM087_48h_THZ2_q4_sorted.counts | cut -f1,2,4,6,8,10,12,14,16,18,20,22,24 | awk 'NR<55402' >> All_THZ2_counts
```

# DeSeq2, multifactorial: http://www.marcjoiret.be/pdfs/DESeq2package.pdf
# 6 and 48h separately
```{r}
library(DESeq2)
THZ2_Counts <- read.delim(file="/media/lcb1/lcb/jwout/Data_Analyses/Data/HiSeq4000_20190327_THZ2_TYR/Allcounts/All_THZ2_counts")

THZ2_Counts_6h <- THZ2_Counts[,1:6]
THZ2_Counts_48h <- THZ2_Counts[,7:12]

#6h
colnames(THZ2_Counts_6h)
coldesign_1 <-data.frame(c("DMSO", "DSMO", "DMSO", "THZ2","THZ2", "THZ2"))
coldesign_2 <-data.frame(c("MM057", "MM074", "MM087", "MM057", "MM074", "MM087"))
coldesign <- cbind(coldesign_1, coldesign_2)
colnames(coldesign)<-c("Treatment", "MMline")
Design<-coldesign
coldesign
dds_THZ2_6h_MF <-DESeqDataSetFromMatrix(countData=THZ2_Counts_6h, colData=coldesign , design= formula(~ MMline + Treatment))
dds_THZ2_6h_MF<-DESeq(dds_THZ2_6h_MF)
res_THZ2_6h_MF<-results(dds_THZ2_6h_MF, contrast=c("Treatment","THZ2","DMSO"))
write.table(res_THZ2_6h_MF,file="THZ2_vs_Ctrl_6h_MF",sep="\t",quote=F)
res_THZ2_6h_MF[rownames(res_THZ2_6h_MF)=="JUNB",]
head(res_THZ2_6h_MF[order(-res_THZ2_6h_MF$log2FoldChange),], 30)
dim(subset(res_THZ2_6h_MF, padj<0.05 & log2FoldChange<0))
rownames(subset(res_THZ2_6h_MF, padj<0.05 & log2FoldChange<0))

#48h
colnames(THZ2_Counts_48h)
coldesign_1 <-data.frame(c("DMSO", "DSMO", "DMSO", "THZ2","THZ2", "THZ2"))
coldesign_2 <-data.frame(c("MM057", "MM074", "MM087", "MM057", "MM074", "MM087"))
coldesign <- cbind(coldesign_1, coldesign_2)
colnames(coldesign)<-c("Treatment", "MMline")
Design<-coldesign
coldesign
dds_THZ2_48h_MF <-DESeqDataSetFromMatrix(countData=THZ2_Counts_48h, colData=coldesign , design= formula(~ MMline + Treatment))
dds_THZ2_48h_MF<-DESeq(dds_THZ2_48h_MF)
res_THZ2_48h_MF<-results(dds_THZ2_48h_MF, contrast=c("Treatment","THZ2","DMSO"))
write.table(res_THZ2_48h_MF,file="THZ2_vs_Ctrl_48h_MF",sep="\t",quote=F)
res_THZ2_48h_MF[rownames(res_THZ2_48h_MF)=="JUNB",]
head(res_THZ2_48h_MF[order(-res_THZ2_48h_MF$log2FoldChange),], 30)
dim(subset(res_THZ2_48h_MF, padj<0.05 & log2FoldChange<0))
rownames(subset(res_THZ2_48h_MF, padj<0.20 & log2FoldChange<0))
dim(subset(res_THZ2_48h_MF, padj<0.05 & log2FoldChange>0))
rownames(subset(res_THZ2_48h_MF, padj<0.05 & log2FoldChange>0))
```

# alltogether
```{r}
colnames(THZ2_Counts)
coldesign_1<-data.frame(c("DMSO", "DSMO", "DMSO", "THZ2","THZ2", "THZ2", "DMSO", "DSMO", "DMSO", "THZ2","THZ2", "THZ2"))
coldesign_2 <-data.frame(c("MM057", "MM074", "MM087", "MM057", "MM074", "MM087", "MM057", "MM074", "MM087", "MM057", "MM074", "MM087"))
coldesign <- cbind(coldesign_1, coldesign_2)
colnames(coldesign)<-c("Treatment", "MMline")
Design<-coldesign
coldesign
dds_THZ2_MF <-DESeqDataSetFromMatrix(countData=THZ2_Counts, colData=coldesign , design= formula(~ MMline + Treatment))
dds_THZ2_MF<-DESeq(dds_THZ2_MF)

#normalized expression values
norm_matrix_deseq_THZ2_MF <- counts(dds_THZ2_MF,normalized=T)
write.table(norm_matrix_deseq_THZ2_MF, file="THZ2_vs_Ctrl_6_and_48h_MF_norm_matrix.txt", sep="\t", quote=F)
```


```{r}
save.image("Workspace_THZ2.RData")
```





